### ISSUE TITLE
What options are available to fix the libdb5.0 reverse incompatibility issue?

### ISSUE THREAD

**Issue by willinspire** [netcoinfoundation/netcoin#19]
## The Conundrum
After pouring over the source files and running several searches on various chat forums etc, I finally stumbled across the notice at the very bottom of the README file concerning the libdb4.x - libdb5.x incompatibility. (Please consider moving this notice from the bottom of the document and putting it into the appropriate section addressed to Ubuntu users.) While I'm glad to have finally discovered the root cause of the issue, I am left with no solutions. 

Reverting my system just so that I can complete compiling a Net Core wallet doesn't really sound worth the hassle. Is there any other way of bridging this gap? If not, are there any plans to update the Net wallet to handle compatibility with libdb5.x ?

## A Few Additional Thoughts
Please consider making a revised installation guide. The current edition is rough and includes several typos, grammar errors, and is very vague. There are also multiple assumptions made as to preexisting knowledge (regarding the package building process, terminal use, fluency with bash, etc etc...). I have a moderate level of experience using Linux and I found the guide to be very difficult to use. I'd love to see the Netcoin project grow in usage and in value, but until the software becomes easy to use that is unlikely to occur.

**Comment by Tepelstreeltje** [comment]
Hi, my apologies for the outdated installation guides but i just haven't had the chance to revise or make it better understandable. It was on my todo list already but the time i'm able to spend on Netcoin is limited so it might take a while. Also English is not my native language so my grammar is not always correct but if you like you are more than welcome to review the updated build guide before release.

For BerkeleyDB, as far as i know, there is no way to update to 4.x due to the fact that 5.x can't handle the 4.x blocks. You need a coinswap to update BDB and at this point there is no way to build Netcoin without BDB.
Bitcoin uses 4.x aswell. In the Bitcoin build guide for unix https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md is a section on how to add a Bitcoin repository for Ubuntu/Debian and install BDB.4.8. It's been a while that i have build a Ubuntu/Debian wallet myself so i can't confirm that the Bitcoin guide is correct still but i assume it is.

For more assistance you can also visit our discord channel https://discord.gg/Fw4new

**Comment by regtable** [comment]
late reply but netcoin builds with bdb-6.2.32 and loads wallets fine wallet files automagically update their "tree" <-- if thats the right definition for the database formatting, they can be upgraded but not downgraded. the choice by bitcoin to stay on 4.x was merely because the block data structure from a 5+ 6+ wallet core would not be able to be sent via zip/bootstrap to a node/core running 4.x meaning it would corrupt the database and re download from 0 anyway.

netcoins deps are now above the standard libs btc uses adn also dependant on linux distro above the sullpied packs via apt-get such as boost is 1.67 on linux distros as the -dev where as now net is compatible with 1.68 available by self compile, 
readmes will be updated.
